[package]
name = "p2p-node-handshake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
bitcoin = "0.30.1"
byteorder = "1.4.3"
chrono = "0.4.31"
